### ISSUE TITLE
Double encoding bug

### ISSUE THREAD

**Issue by fractalf** [kvz/phpjs#206]
This fails:
```js
htmlentities('"'); // result: &amp;quot;
```
Reason:
The object <b>hash_map</b> returned from <b>get_html_translation_table</b> puts <b>"</b> (code 34) before <b>&</b> (code 39) when looping through.

An object won't guarantee any order of it's properties, so hash_map should be an array. Basically a lot of the variables defined in get_html_translation_table should be arrays, not objects

**Comment by kukawski** [comment]
OK, it should work now.
