### ISSUE TITLE
strtotime works differently in different browsers

### ISSUE THREAD

**Issue by evgenius** [kvz/phpjs#222]
`strtotime('2015-04-15T20:33:59+02:00');`
returns `1429122839` in Chrome and `false` in the rest browsers.

The reason is that the function converts the date string to lower case but browsers (except Chrome) can't parse such strings.
So `Date.parse('2015-04-15t20:33:59+02:00')` is `NaN` in non-Chrome browsers.

I am going to fix it.

Thanks @plepe for catching this bug.

**Comment by theaqua** [comment]
Why you don't use [moment.js](http://momentjs.com)?

**Comment by evgenius** [comment]
@theaqua Because it's heavy compared to this function.
`strtotime` is used in Twig.js I contribute to.
