### ISSUE TITLE
Consider using "bin" property of package.json to reference CLI app

### ISSUE THREAD

**Issue by niksy** [kvz/phpjs#274]
Using [`bin` property of package.json](https://docs.npmjs.com/files/package.json#bin) you can easily reference CLI app and make it available to npm scripts.

Instead of this:

```json
{
  "build-phpjs": "node node_modules/phpjs/bin/phpjs.js --action buildnpm --name nl2br"
}
```

It can be used like this:

```json
{
  "build-phpjs": "phpjs.js --action buildnpm --name nl2br"
}
```

Is this something you would consider using?

**Comment by kvz** [comment]
I think that makes sense yes!
