### ISSUE TITLE
Uncaught ReferenceError: phpjs is not defined

### ISSUE THREAD

**Issue by LiXunGuan** [kvz/phpjs#286]
in webpack use phpjs
```javascript
var php = require('phpjs');
php.echo(php.sprintf('Hey, %s : )', 'you'));
```
![phpjs.png](https://ooo.0o0.ooo/2016/04/04/5702224481e95.png)

**Comment by kvz** [comment]
Hi, 

While I'm not sure what the issue is, please don't include php.js and ship it to webbrowsers, it's way too big and unstable for that.

**Comment by LiXunGuan** [comment]
OK，3Q
